# Data Structures and Processing

## Week 9: Image Processing

### Remarks:

1. Install the libraries listed below using your package manager.  An example of installing the library `numpy` is to issue a the following command on a terminal (in Ubuntu) `python3 -m pip install numpy`.

2. Make sure that you are following the conventions.  For examples, `import numpy as np`, which imports pandas packages and sets the abbreviation for it.

3. Do not import the packages without the short names, unless it is intentional.  Doing so might lead to a namespace conflict, or unintended uses of functions coming from two libraries as a part of different implementations.

4. We are assigning `None` to variables and use `pass` in the body of the functions, where we expect a solution from you.  Please replace these values and statements with your solution.

The exercises in this notebook are aligned with the material provided for the lecture.

### Load Libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import imageio.v3 as iio
import ipympl
import skimage as ski
import imageio.v3 as iio


### Task 1: Arrays or Lists to Images

A basic unit of  digital image is a pixel.  These pixels are arranged together in horizontal and vertical directions on a screen in a rectangular shape. This rectangular arrangement constitute an image. A pixel, on the other hand, is triplet of numbers. These numbers might have different ranges depending upon the kind of format used.  For example, an image having an `RGB` format has the numbers ranged between 0 and 255.

An image seen as an arrangement of pixels, with pixels having a list of three numbers, does not have to involve `numpy` arrays, but rather it might be a list of nested lists with the inner most list having length 3.  The Python library `matplotlib`, then takes care of the necessary conversions to make sure that when the imags is plotted, then it is done exactly how it was meant to be.  If we work with the `numpy` arrays, then we can use the power of the library to use different methods, functions and access different attributes to better work with the images at hand.

Your task is to create an numpy array named `img` with the shape `(3,4,3)` and display it in the notebook.  It is not important what type of numbers are filled in at the deepest level. For this you could generate those numbers randomly using `np.random`.

In [2]:
# Your solutions goes here.
#np.random.randin(min,max,size=shape)
img = np.array([np.random.randint(1,10,size=(3,4,3))])
img
# Display picture below.

array([[[[5, 9, 3],
         [1, 6, 8],
         [6, 7, 5],
         [7, 9, 2]],

        [[8, 2, 3],
         [6, 5, 5],
         [9, 3, 2],
         [6, 6, 1]],

        [[1, 6, 7],
         [8, 7, 3],
         [3, 2, 7],
         [8, 8, 9]]]])

## Task 2: Color Channels

Each pixel has three color channels: `red`, `green` and `blue`.  Given an image, if we want to remove a channel from it, then we have to put 0 at the corresponding place. This task of switching channels off becomes even simpler if we use the `numpy` arrays, because we can use their arithmetics to do so.

In the following block, we define an `image` as a `numpy` array. Your task is to display three pictures with:
1. `red` channel removed,
2. `green` channel removed,
3. `blue` channel removed.

Generate extra blocks below if there is a need.

In [3]:
# Evaluate this block to make sure the variable is set to a correct value.

image = np.array([[[112,160,124],[51,159,107],[243,146,17],[78,136,42],[248,1,123],[2,243,234],[34,172,157],[109,6,183],[224,147,3],[136,248,206]],[[34,156,245],[212,99,237],[67,127,58],[249,134,217],[245,161,83],[129,165,115],[41,19,153],[74,249,251],[99,186,100],[50,26,171]],[[210,246,125],[119,197,50],[68,221,250],[52,232,121],[210,141,248],[46,85,213],[221,3,61],[45,119,58],[106,102,92],[200,57,76]],[[14,126,116],[197,174,12],[201,118,10],[179,66,143],[4,133,91],[6,217,53],[92,163,110],[172,163,57],[112,99,182],[200,216,19]],[[105,183,48],[74,238,92],[8,129,153],[226,78,134],[70,122,12],[222,93,30],[229,144,56],[190,101,22],[237,180,217],[112,175,108]],[[55,69,169],[80,185,45],[88,174,186],[187,162,119],[150,165,86],[248,188,250],[2,109,48],[185,246,63],[1,167,101],[60,0,162]],[[70,115,127],[45,83,135],[133,166,115],[177,112,113],[85,117,47],[237,189,94],[36,201,174],[159,154,91],[13,121,67],[72,112,64]],[[202,161,68],[131,231,8],[208,32,66],[239,218,56],[50,160,171],[140,28,251],[168,0,22],[170,36,94],[98,241,219],[84,143,94]],[[237,118,109],[244,208,116],[168,123,136],[17,4,132],[237,63,85],[16,76,111],[144,79,133],[135,78,200],[173,105,225],[62,134,234]],[[7,6,211],[114,220,181],[173,127,40],[60,192,121],[170,143,70],[169,168,116],[100,124,208],[253,251,143],[136,99,88],[201,226,84]],[[249,215,242],[138,117,102],[223,5,147],[225,30,37],[148,233,202],[220,92,232],[97,93,223],[205,115,182],[169,54,92],[228,120,230]],[[170,77,125],[168,23,25],[190,150,48],[170,129,104],[52,24,225],[1,7,125],[252,150,24],[231,1,168],[1,66,189],[216,123,239]],[[174,93,71],[17,39,186],[91,186,66],[82,58,176],[25,211,186],[140,184,172],[0,82,155],[252,252,170],[119,84,58],[45,121,138]],[[126,77,80],[232,25,230],[89,241,168],[9,172,251],[169,35,29],[204,204,245],[159,40,73],[196,72,70],[4,35,247],[25,26,71]],[[96,208,147],[108,45,92],[123,192,234],[26,41,79],[113,236,101],[38,168,41],[104,242,252],[228,42,156],[14,54,228],[23,154,179]],[[26,68,124],[131,41,100],[31,247,59],[80,9,87],[128,213,86],[107,113,85],[41,189,209],[207,178,169],[253,225,57],[54,184,61]],[[183,69,224],[114,215,149],[141,5,76],[76,138,62],[52,101,199],[70,246,21],[65,227,157],[216,114,156],[153,62,11],[241,202,12]],[[40,121,60],[39,199,2],[98,7,29],[6,7,42],[234,185,224],[71,170,158],[252,194,147],[221,28,204],[137,70,233],[172,249,235]],[[73,118,175],[126,109,179],[33,222,16],[202,243,209],[132,244,157],[135,20,145],[161,2,203],[65,253,96],[102,130,239],[157,220,5]],[[96,8,199],[128,49,254],[162,196,159],[150,177,254],[89,159,100],[185,73,150],[209,100,127],[159,197,49],[217,0,141],[239,32,9]]])
image.shape

(20, 10, 3)

In [4]:
# Your solution to red channel removed.
img_r = image * [0,1,1]
img_r

array([[[  0, 160, 124],
        [  0, 159, 107],
        [  0, 146,  17],
        [  0, 136,  42],
        [  0,   1, 123],
        [  0, 243, 234],
        [  0, 172, 157],
        [  0,   6, 183],
        [  0, 147,   3],
        [  0, 248, 206]],

       [[  0, 156, 245],
        [  0,  99, 237],
        [  0, 127,  58],
        [  0, 134, 217],
        [  0, 161,  83],
        [  0, 165, 115],
        [  0,  19, 153],
        [  0, 249, 251],
        [  0, 186, 100],
        [  0,  26, 171]],

       [[  0, 246, 125],
        [  0, 197,  50],
        [  0, 221, 250],
        [  0, 232, 121],
        [  0, 141, 248],
        [  0,  85, 213],
        [  0,   3,  61],
        [  0, 119,  58],
        [  0, 102,  92],
        [  0,  57,  76]],

       [[  0, 126, 116],
        [  0, 174,  12],
        [  0, 118,  10],
        [  0,  66, 143],
        [  0, 133,  91],
        [  0, 217,  53],
        [  0, 163, 110],
        [  0, 163,  57],
        [  0,  99, 182],
        [  0, 216, 

In [5]:
# Your solution to green channel removed.
img_g = image * [1,0,1]
img_g

array([[[112,   0, 124],
        [ 51,   0, 107],
        [243,   0,  17],
        [ 78,   0,  42],
        [248,   0, 123],
        [  2,   0, 234],
        [ 34,   0, 157],
        [109,   0, 183],
        [224,   0,   3],
        [136,   0, 206]],

       [[ 34,   0, 245],
        [212,   0, 237],
        [ 67,   0,  58],
        [249,   0, 217],
        [245,   0,  83],
        [129,   0, 115],
        [ 41,   0, 153],
        [ 74,   0, 251],
        [ 99,   0, 100],
        [ 50,   0, 171]],

       [[210,   0, 125],
        [119,   0,  50],
        [ 68,   0, 250],
        [ 52,   0, 121],
        [210,   0, 248],
        [ 46,   0, 213],
        [221,   0,  61],
        [ 45,   0,  58],
        [106,   0,  92],
        [200,   0,  76]],

       [[ 14,   0, 116],
        [197,   0,  12],
        [201,   0,  10],
        [179,   0, 143],
        [  4,   0,  91],
        [  6,   0,  53],
        [ 92,   0, 110],
        [172,   0,  57],
        [112,   0, 182],
        [200,   0, 

In [6]:
# Your solution to blue channel removed.
img_b = image * [1,1,0]
img_b

array([[[112, 160,   0],
        [ 51, 159,   0],
        [243, 146,   0],
        [ 78, 136,   0],
        [248,   1,   0],
        [  2, 243,   0],
        [ 34, 172,   0],
        [109,   6,   0],
        [224, 147,   0],
        [136, 248,   0]],

       [[ 34, 156,   0],
        [212,  99,   0],
        [ 67, 127,   0],
        [249, 134,   0],
        [245, 161,   0],
        [129, 165,   0],
        [ 41,  19,   0],
        [ 74, 249,   0],
        [ 99, 186,   0],
        [ 50,  26,   0]],

       [[210, 246,   0],
        [119, 197,   0],
        [ 68, 221,   0],
        [ 52, 232,   0],
        [210, 141,   0],
        [ 46,  85,   0],
        [221,   3,   0],
        [ 45, 119,   0],
        [106, 102,   0],
        [200,  57,   0]],

       [[ 14, 126,   0],
        [197, 174,   0],
        [201, 118,   0],
        [179,  66,   0],
        [  4, 133,   0],
        [  6, 217,   0],
        [ 92, 163,   0],
        [172, 163,   0],
        [112,  99,   0],
        [200, 216, 

## Task 3: Manipulating Pixels

Reconsider the example of `numpy` array `image` from a previous task. To make sure that the value of this arrays reverts back to our desired value, we provide it below one more time.

Your task is to replace each individual number in a pixel with the average value of the pixel and display the image. For this, define a new array `image_avg` obtained by averaging, as just desribed.

In [7]:
# Your solution goes here.
image = np.array([[[112,160,124],[51,159,107],[243,146,17],[78,136,42],[248,1,123],[2,243,234],[34,172,157],[109,6,183],[224,147,3],[136,248,206]],[[34,156,245],[212,99,237],[67,127,58],[249,134,217],[245,161,83],[129,165,115],[41,19,153],[74,249,251],[99,186,100],[50,26,171]],[[210,246,125],[119,197,50],[68,221,250],[52,232,121],[210,141,248],[46,85,213],[221,3,61],[45,119,58],[106,102,92],[200,57,76]],[[14,126,116],[197,174,12],[201,118,10],[179,66,143],[4,133,91],[6,217,53],[92,163,110],[172,163,57],[112,99,182],[200,216,19]],[[105,183,48],[74,238,92],[8,129,153],[226,78,134],[70,122,12],[222,93,30],[229,144,56],[190,101,22],[237,180,217],[112,175,108]],[[55,69,169],[80,185,45],[88,174,186],[187,162,119],[150,165,86],[248,188,250],[2,109,48],[185,246,63],[1,167,101],[60,0,162]],[[70,115,127],[45,83,135],[133,166,115],[177,112,113],[85,117,47],[237,189,94],[36,201,174],[159,154,91],[13,121,67],[72,112,64]],[[202,161,68],[131,231,8],[208,32,66],[239,218,56],[50,160,171],[140,28,251],[168,0,22],[170,36,94],[98,241,219],[84,143,94]],[[237,118,109],[244,208,116],[168,123,136],[17,4,132],[237,63,85],[16,76,111],[144,79,133],[135,78,200],[173,105,225],[62,134,234]],[[7,6,211],[114,220,181],[173,127,40],[60,192,121],[170,143,70],[169,168,116],[100,124,208],[253,251,143],[136,99,88],[201,226,84]],[[249,215,242],[138,117,102],[223,5,147],[225,30,37],[148,233,202],[220,92,232],[97,93,223],[205,115,182],[169,54,92],[228,120,230]],[[170,77,125],[168,23,25],[190,150,48],[170,129,104],[52,24,225],[1,7,125],[252,150,24],[231,1,168],[1,66,189],[216,123,239]],[[174,93,71],[17,39,186],[91,186,66],[82,58,176],[25,211,186],[140,184,172],[0,82,155],[252,252,170],[119,84,58],[45,121,138]],[[126,77,80],[232,25,230],[89,241,168],[9,172,251],[169,35,29],[204,204,245],[159,40,73],[196,72,70],[4,35,247],[25,26,71]],[[96,208,147],[108,45,92],[123,192,234],[26,41,79],[113,236,101],[38,168,41],[104,242,252],[228,42,156],[14,54,228],[23,154,179]],[[26,68,124],[131,41,100],[31,247,59],[80,9,87],[128,213,86],[107,113,85],[41,189,209],[207,178,169],[253,225,57],[54,184,61]],[[183,69,224],[114,215,149],[141,5,76],[76,138,62],[52,101,199],[70,246,21],[65,227,157],[216,114,156],[153,62,11],[241,202,12]],[[40,121,60],[39,199,2],[98,7,29],[6,7,42],[234,185,224],[71,170,158],[252,194,147],[221,28,204],[137,70,233],[172,249,235]],[[73,118,175],[126,109,179],[33,222,16],[202,243,209],[132,244,157],[135,20,145],[161,2,203],[65,253,96],[102,130,239],[157,220,5]],[[96,8,199],[128,49,254],[162,196,159],[150,177,254],[89,159,100],[185,73,150],[209,100,127],[159,197,49],[217,0,141],[239,32,9]]])

image_avg = np.mean(image, axis=2)
image_avg
# Display the resulting array

array([[132.        , 105.66666667, 135.33333333,  85.33333333,
        124.        , 159.66666667, 121.        ,  99.33333333,
        124.66666667, 196.66666667],
       [145.        , 182.66666667,  84.        , 200.        ,
        163.        , 136.33333333,  71.        , 191.33333333,
        128.33333333,  82.33333333],
       [193.66666667, 122.        , 179.66666667, 135.        ,
        199.66666667, 114.66666667,  95.        ,  74.        ,
        100.        , 111.        ],
       [ 85.33333333, 127.66666667, 109.66666667, 129.33333333,
         76.        ,  92.        , 121.66666667, 130.66666667,
        131.        , 145.        ],
       [112.        , 134.66666667,  96.66666667, 146.        ,
         68.        , 115.        , 143.        , 104.33333333,
        211.33333333, 131.66666667],
       [ 97.66666667, 103.33333333, 149.33333333, 156.        ,
        133.66666667, 228.66666667,  53.        , 164.66666667,
         89.66666667,  74.        ],
       [10

## Task 4: Saving Images to files

Reconsider the previous task, where you have created an image by averaging different channels.

Your task is to store the image to a file named `random-image-01.jpg`.

In [8]:
iio.imwrite("random-image-01.jpg", image_avg)
#i tried this doesnt work so i googled and found
#a solution which i used in next assignment

OSError: cannot write mode F as JPEG

## Task 5: Reading Images in from files

We provide an image `beads.jpg` with this notebook. Any other image would do the job too.

Your task is to
1. read an image to a variable `image` using the Python library called `imageio`,
2. obtain a new array `image_r` that contains only the `red` channel.
3. save the `image_r` to a file named `beads_r.png`.

In [ ]:
# Your solution goes here
image = iio.imread(uri="beads.jpg")
image_float = image.astype(float)
image_r = image_float * [1,0,0]
image_r_uint8 = image_r.astype(np.uint8) #googled
iio.imwrite("beads_r.jpg",image_r_uint8)

## Task 6: Image I/O and Manipulation

Define a function `image_averaged` with two string arguments: `file_in` and `file_out`. This function must do the following

1. reads the image pointed to by the path `file_in`,
2. averages each pixel using the channels in that pixel,
3. saves the averaged array as a image to a file using `file_out`,
4. returns `file_out`

In [ ]:
# Your solution goes here.
def image_averaged(file_in, file_out):
    image = iio.imread(uri=file_in)
    image_avg = np.mean(image, axis=2)
    image_avg_uint8 = image_avg.astype(np.uint8)
    iio.imwrite(file_out, image_avg_uint8)
    

In [ ]:
# Test your function `image_averaged` on a sample file `beads.jpg`.
image_averaged("beads.jpg","outputfile.jpg")

## Task 7: Image Manipulation: Crop or Slice

Write down a function named `image_right_half` that takes two arguments `file_in` and `file_out` and it does the following:

1. reads the image `file_in`,
2. crops the right half of the image,
3. saves the new image to `file_out`,
4. returns `file_out`.

In [ ]:
# Your solutios goes here.
def image_right_half(file_in, file_out):
    image = iio.imread(uri=file_in)
    image = np.array(image)
    half_image = image[:, image.shape[1] // 2:]
    plt.imshow(half_image)
    image_avg_uint8 = half_image.astype(np.uint8)
    iio.imwrite(file_out, image_avg_uint8)


In [ ]:
# Test your function `image_right_half` on a sample file `beads.jpg`
image_right_half("beads.jpg","outputfile2.jpg")

## Task 8: Image Manipulation: Masking

Masking might be an expensive operation, because it amounts to turning of undesired values in pixels.  It might be even slower, if we worked with a huge image and tried to view the image in this Jupyter notebook.

Your task is to write down a function `image_mask`, which takes six arguments:

1. `file_in`: image to be read in.
2. `file_out`: image to be written to.
3. `x1,y1` the upper right corner of the rectangle for the mask.
4. `x2,y2` lower right corder or the rentangle for the mask.

The function `image_mask` takes the `file_in` applies the mask and then writes the resulting image to `file_out`.

In [ ]:
# Your solution goes here.
from skimage.draw import rectangle
def image_mask( file_in, file_out, x1, y1, x2, y2):
    image = iio.imread(uri=file_in)
    mask = np.ones(image.shape[0:2], dtype=bool)
    rr, cc = rectangle(start=(x1, y1), end=(x2, y2))
    mask[rr,cc] = False
    image[mask] = 0
    plt.imshow(image)
    image_avg_uint8 = image.astype(np.uint8)
    iio.imwrite(file_out, image_avg_uint8)
    

In [ ]:
# Test your function on a sample image.
image_mask("beads.jpg","outputfile3.jpg",357,44,740,700)

## Task 9: Histograms

Write down a function `image_hist_red` that takes the two arguments: `file_in` and `file_out`.  This function plots a histrogram of the `red` channel and stores it in `file_out`.

In [ ]:
# Your solution goes here.

def image_hist_red(file_in, file_out):
    image = iio.imread(uri=file_in)
    image = image * [1,0,0]
    counts, edges = np.histogram(image.flatten(), bins=256, range=(0,256))
    plt.plot(edges[:-1], counts)
    
    plt.savefig(file_out)
    


In [ ]:
# Test your function `image_hist_red` on a sample image.
image_hist_red("beads.jpg","outputfile4.jpg")

## Task 10: Object Identification (Bonus)

Consider the image `sudoku.png` in the attachment to this notebook.

Write down a function `image_object_count` that takes a `file_in` as the only argument and returns the number of objects on it.

For help, please refer to the associated lecture material.

In [ ]:
# Your solution goes here
def image_object_count(file_in):
    image = iio.imread(uri=file_in)
    gray_shapes = ski.color.rgb2gray(image)
    blurred_shapes = ski.filters.gaussian(gray_shapes, sigma=1.0)
    t = 0.8
    binary_mask = blurred_shapes < t
    labeled_image, count = ski.measure.label(binary_mask, connectivity=1, return_num=True)
    print(f'Number of objects on the image: {count}')

In [ ]:
# Test your function against the image sudoku.png
# Your function should return 29
image_object_count("sudoku.png")

Number of objects on the image: 29
